### ISSUE TITLE
ENHANCEMENT: Update Meta Tags for improved SEO and social sharing.

### ISSUE THREAD

**Issue by neeru24** [AlfiyaSiddique/TastyTrails#409]
### Is there an existing issue raised for this?

- [X] I have searched the existing issues

### Describe the improvement

The meta title and description for the website need to be updated to improve SEO and attract more visitors.

- Revise the meta title to include relevant keywords for UI design.
- Update the meta description to reflect the homepage content and include targeted keywords.

### Component

This can be efficiently accomplished by simply adding relevant keywords to the existing meta title and description in the HTML code.

### It should be implemented because

By optimizing these meta tags, we can improve the website’s search engine visibility and attract more visitors.

### Would you like to work on this issue?

Yes

### Terms & Conditions

- [X] I agree to follow the Code of Conduct
- [X] I'm a GSSOC'24 Ext contributor

**Comment by AlfiyaSiddique** [comment]
@neeru24 to small change to be assigned
